# How to throw exceptions

<!-- TOC -->

- [1. Throwing a Checked Exception](#1-throwing-a-checked-exception)
- [2. Throwing an Unchecked Exception](#2-throwing-an-unchecked-exception)
- [3. Rethrowing](#3-rethrowing)
- [4. Wrapping](#4-wrapping)
- [5. Rethrowing Throwable or _Exception*?](#5-rethrowing-throwable-or-exception)
- [6. Exception Inheritance](#6-exception-inheritance)

<!-- /TOC -->

Sometimes, we don't want to handle exceptions. In such cases, we should only concern ourselves with generating them when needed and allowing someone else, calling our method, to handle them appropriately.

## 1. Throwing a Checked Exception

When something goes wrong, like the number of users currently connecting to our service exceeding the maximum amount for the server to handle seamlessly, we want to throw an exception to indicate an exceptional situation:

```java
public void countUsers() throws TooManyUsersException {
    int numberOfUsers = 0;
        while(numberOfUsers < 500) {
            // some code
            numberOfUsers++;
    }
    throw new TooManyUsersException("The number of users exceeds our maximum recommended amount.");
}
```

This code will increase `numberOfUsers` until it exceeds the maximum recommended amount, after which it will throw an exception. Since this is a checked exception, we have to add the `throws` clause in the method signature.

To define an exception like this is as easy as writing the following:

```java
public class TooManyUsersException extends Exception {
    public TooManyUsersException(String message) {
        super(message);
    }
}
```

## 2. Throwing an Unchecked Exception

Throwing runtime exceptions usually boils down to validation of input, since they most often occur due to faulty input - either in the form of an `IllegalArgumentException`, `NumberFormatException`, `ArrayIndexOutOfBoundsException`, or a `NullPointerException`:

```java
public void authenticateUser(String username) throws UserNotAuthenticatedException {
    if(!isAuthenticated(username)) {
        throw new UserNotAuthenticatedException("User is not authenticated!");
    }
}
```

Since we're throwing a runtime exception, there's no need to include it in the method signature, like in the example above, but **it's often considered good practice to do so, at least for the sake of documentation.**

Again, defining a custom runtime exception like this one is as easy as:

```java
public class UserNotAuthenticatedException extends RuntimeException {
    public UserNotAuthenticatedException(String message) {
        super(message);
    }
}
```

## 3. Rethrowing

Rethrowing an exception was mentioned before so here's a short section to clarify:

```java
public String readFirstLine(String url) throws FileNotFoundException {
    try {
        Scanner scanner = new Scanner(new File(url));
        return scanner.nextLine();
    } catch(FileNotFoundException ex) {
        throw ex;
    }
}
```

Rethrowing refers to the process of throwing an already caught exception, rather than throwing a new one.

## 4. Wrapping

Wrapping, on the other hand, refers to the process of wrapping an already caught exception, within another exception:

```java
public String readFirstLine(String url) throws FileNotFoundException {
    try {
        Scanner scanner = new Scanner(new File(url));
        return scanner.nextLine();
    } catch(FileNotFoundException ex) {
        throw new SomeOtherException(ex); 
    }
}
```

## 5. Rethrowing Throwable or _Exception*?

These top-level classes can be caught and rethrown, but how to do so can vary:

```java
public void parseFile(String filePath) {
    try {
        throw new NumberFormatException();
    } catch (Throwable t) {
        throw t;
    }
}
```

In this case, the method is throwing a `NumberFormatException` which is a runtime exception. Because of this, we don't have to mark the method signature with either `NumberFormatException` or `Throwable`.

However, if we throw a checked exception within the method:

```java
public void parseFile(String filePath) throws Throwable {
    try {
        throw new IOException();
    } catch (Throwable t) {
        throw t;
    }
}
```

We now have to declare that the method is throwing a `Throwable`. Why this can be useful is a broad topic that is out of scope for this blog, but there are usages for this specific case.

## 6. Exception Inheritance

Subclasses that inherit a method can only throw fewer checked exceptions than their superclass:

```java
public class SomeClass {
   public void doSomething() throws SomeException {
        // some code
    }
}
```

With this definition, the following method will cause a compiler error:

```java
public class OtherClass extends SomeClass {
    @Override
    public void doSomething() throws OtherException {
        // some code
    }
}
```
